#line 2 "flex_lexer.cpp"

#line 4 "flex_lexer.cpp"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

#ifdef yy_create_buffer
#define ff__create_buffer_ALREADY_DEFINED
#else
#define yy_create_buffer ff__create_buffer
#endif

#ifdef yy_delete_buffer
#define ff__delete_buffer_ALREADY_DEFINED
#else
#define yy_delete_buffer ff__delete_buffer
#endif

#ifdef yy_scan_buffer
#define ff__scan_buffer_ALREADY_DEFINED
#else
#define yy_scan_buffer ff__scan_buffer
#endif

#ifdef yy_scan_string
#define ff__scan_string_ALREADY_DEFINED
#else
#define yy_scan_string ff__scan_string
#endif

#ifdef yy_scan_bytes
#define ff__scan_bytes_ALREADY_DEFINED
#else
#define yy_scan_bytes ff__scan_bytes
#endif

#ifdef yy_init_buffer
#define ff__init_buffer_ALREADY_DEFINED
#else
#define yy_init_buffer ff__init_buffer
#endif

#ifdef yy_flush_buffer
#define ff__flush_buffer_ALREADY_DEFINED
#else
#define yy_flush_buffer ff__flush_buffer
#endif

#ifdef yy_load_buffer_state
#define ff__load_buffer_state_ALREADY_DEFINED
#else
#define yy_load_buffer_state ff__load_buffer_state
#endif

#ifdef yy_switch_to_buffer
#define ff__switch_to_buffer_ALREADY_DEFINED
#else
#define yy_switch_to_buffer ff__switch_to_buffer
#endif

#ifdef yypush_buffer_state
#define ff_push_buffer_state_ALREADY_DEFINED
#else
#define yypush_buffer_state ff_push_buffer_state
#endif

#ifdef yypop_buffer_state
#define ff_pop_buffer_state_ALREADY_DEFINED
#else
#define yypop_buffer_state ff_pop_buffer_state
#endif

#ifdef yyensure_buffer_stack
#define ff_ensure_buffer_stack_ALREADY_DEFINED
#else
#define yyensure_buffer_stack ff_ensure_buffer_stack
#endif

#ifdef yylex
#define ff_lex_ALREADY_DEFINED
#else
#define yylex ff_lex
#endif

#ifdef yyrestart
#define ff_restart_ALREADY_DEFINED
#else
#define yyrestart ff_restart
#endif

#ifdef yylex_init
#define ff_lex_init_ALREADY_DEFINED
#else
#define yylex_init ff_lex_init
#endif

#ifdef yylex_init_extra
#define ff_lex_init_extra_ALREADY_DEFINED
#else
#define yylex_init_extra ff_lex_init_extra
#endif

#ifdef yylex_destroy
#define ff_lex_destroy_ALREADY_DEFINED
#else
#define yylex_destroy ff_lex_destroy
#endif

#ifdef yyget_debug
#define ff_get_debug_ALREADY_DEFINED
#else
#define yyget_debug ff_get_debug
#endif

#ifdef yyset_debug
#define ff_set_debug_ALREADY_DEFINED
#else
#define yyset_debug ff_set_debug
#endif

#ifdef yyget_extra
#define ff_get_extra_ALREADY_DEFINED
#else
#define yyget_extra ff_get_extra
#endif

#ifdef yyset_extra
#define ff_set_extra_ALREADY_DEFINED
#else
#define yyset_extra ff_set_extra
#endif

#ifdef yyget_in
#define ff_get_in_ALREADY_DEFINED
#else
#define yyget_in ff_get_in
#endif

#ifdef yyset_in
#define ff_set_in_ALREADY_DEFINED
#else
#define yyset_in ff_set_in
#endif

#ifdef yyget_out
#define ff_get_out_ALREADY_DEFINED
#else
#define yyget_out ff_get_out
#endif

#ifdef yyset_out
#define ff_set_out_ALREADY_DEFINED
#else
#define yyset_out ff_set_out
#endif

#ifdef yyget_leng
#define ff_get_leng_ALREADY_DEFINED
#else
#define yyget_leng ff_get_leng
#endif

#ifdef yyget_text
#define ff_get_text_ALREADY_DEFINED
#else
#define yyget_text ff_get_text
#endif

#ifdef yyget_lineno
#define ff_get_lineno_ALREADY_DEFINED
#else
#define yyget_lineno ff_get_lineno
#endif

#ifdef yyset_lineno
#define ff_set_lineno_ALREADY_DEFINED
#else
#define yyset_lineno ff_set_lineno
#endif

#ifdef yyget_column
#define ff_get_column_ALREADY_DEFINED
#else
#define yyget_column ff_get_column
#endif

#ifdef yyset_column
#define ff_set_column_ALREADY_DEFINED
#else
#define yyset_column ff_set_column
#endif

#ifdef yywrap
#define ff_wrap_ALREADY_DEFINED
#else
#define yywrap ff_wrap
#endif

#ifdef yyget_lval
#define ff_get_lval_ALREADY_DEFINED
#else
#define yyget_lval ff_get_lval
#endif

#ifdef yyset_lval
#define ff_set_lval_ALREADY_DEFINED
#else
#define yyset_lval ff_set_lval
#endif

#ifdef yyget_lloc
#define ff_get_lloc_ALREADY_DEFINED
#else
#define yyget_lloc ff_get_lloc
#endif

#ifdef yyset_lloc
#define ff_set_lloc_ALREADY_DEFINED
#else
#define yyset_lloc ff_set_lloc
#endif

#ifdef yyalloc
#define ff_alloc_ALREADY_DEFINED
#else
#define yyalloc ff_alloc
#endif

#ifdef yyrealloc
#define ff_realloc_ALREADY_DEFINED
#else
#define yyrealloc ff_realloc
#endif

#ifdef yyfree
#define ff_free_ALREADY_DEFINED
#else
#define yyfree ff_free
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* An opaque pointer. */
#ifndef YY_TYPEDEF_YY_SCANNER_T
#define YY_TYPEDEF_YY_SCANNER_T
typedef void* yyscan_t;
#endif

/* For convenience, these vars (plus the bison vars far below)
   are macros in the reentrant scanner. */
#define yyin yyg->yyin_r
#define yyout yyg->yyout_r
#define yyextra yyg->yyextra_r
#define yyleng yyg->yyleng_r
#define yytext yyg->yytext_r
#define yylineno (YY_CURRENT_BUFFER_LVALUE->yy_bs_lineno)
#define yycolumn (YY_CURRENT_BUFFER_LVALUE->yy_bs_column)
#define yy_flex_debug yyg->yy_flex_debug_r

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yyg->yy_start = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yyg->yy_start - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin , yyscanner )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = yyg->yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yyg->yy_c_buf_p = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, yyg->yytext_ptr , yyscanner )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( yyg->yy_buffer_stack \
                          ? yyg->yy_buffer_stack[yyg->yy_buffer_stack_top] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE yyg->yy_buffer_stack[yyg->yy_buffer_stack_top]

void yyrestart ( FILE *input_file , yyscan_t yyscanner );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer , yyscan_t yyscanner );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size , yyscan_t yyscanner );
void yy_delete_buffer ( YY_BUFFER_STATE b , yyscan_t yyscanner );
void yy_flush_buffer ( YY_BUFFER_STATE b , yyscan_t yyscanner );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer , yyscan_t yyscanner );
void yypop_buffer_state ( yyscan_t yyscanner );

static void yyensure_buffer_stack ( yyscan_t yyscanner );
static void yy_load_buffer_state ( yyscan_t yyscanner );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file , yyscan_t yyscanner );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER , yyscanner)

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size , yyscan_t yyscanner );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str , yyscan_t yyscanner );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len , yyscan_t yyscanner );

void *yyalloc ( yy_size_t , yyscan_t yyscanner );
void *yyrealloc ( void *, yy_size_t , yyscan_t yyscanner );
void yyfree ( void * , yyscan_t yyscanner );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (yyscanner); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE , yyscanner); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (yyscanner); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE , yyscanner); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define ff_wrap(yyscanner) (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

typedef int yy_state_type;

#define yytext_ptr yytext_r

static yy_state_type yy_get_previous_state ( yyscan_t yyscanner );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  , yyscan_t yyscanner);
static int yy_get_next_buffer ( yyscan_t yyscanner );
static void yynoreturn yy_fatal_error ( const char* msg , yyscan_t yyscanner );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yyg->yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yyg->yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yyg->yy_c_buf_p = yy_cp;
#define YY_NUM_RULES 135
#define YY_END_OF_BUFFER 136
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[536] =
    {   0,
        0,    0,    0,    0,    0,    0,  136,  134,  133,  133,
      134,  134,  129,  130,  132,  132,  132,  132,  132,  132,
      132,  132,  132,  132,  132,  132,  132,  132,  132,  132,
      132,  132,  132,  132,  132,  135,  133,    0,  130,  129,
      128,  132,  132,  132,  132,  132,  132,  132,  132,  132,
       48,  132,  132,  132,  132,   53,  132,  132,  132,  132,
      132,  132,  132,  132,  132,  132,  132,  132,  132,  132,
      132,  132,  132,  132,  132,  132,  132,  132,  132,  132,
      132,   55,  132,   45,  132,  132,  132,   54,  132,  132,
      132,  132,  132,  132,  132,  132,  132,  132,  132,  132,

      132,  132,  132,  132,  132,  132,  132,   56,  132,  132,
      132,  132,  132,  132,  131,  128,  132,  132,  132,   44,
      132,   50,  132,  132,  132,  132,    1,  132,  132,  132,
      132,  132,   24,  132,  132,  132,  132,  132,  132,  132,
      132,  132,  132,  132,  132,  132,  132,  132,  132,  132,
      132,  132,  132,  132,  132,   66,  132,  132,   65,  132,
      132,   47,  132,  132,  132,  132,  132,  132,  132,  132,
      132,  132,  132,  132,  132,  132,  132,  132,   43,  132,
      132,  132,  132,  132,  132,  132,  132,  132,  132,   64,
      132,   26,  132,  132,  132,   46,  132,  132,  132,  132,

      132,  132,  132,  132,  132,  132,  132,  132,  132,  132,
      132,    8,   31,   51,    2,  132,  132,  132,  132,  132,
      132,   67,  132,   69,  132,  132,   74,  132,  132,   77,
      132,  132,   36,    6,  132,  132,  132,   82,   83,  132,
      132,   87,   88,  132,   39,  132,   10,   40,  132,  132,
      132,  132,   18,  132,  132,  132,  132,  132,   90,  132,
       94,  132,  132,  132,  132,  132,  132,  132,  132,  132,
      132,  132,   23,  103,  132,  105,  132,  132,  132,   27,
      132,  132,  108,  132,  132,  132,  132,  132,  116,  132,
      132,  132,   63,  132,   52,  132,  132,  132,   30,  132,

      132,  132,  132,  132,  132,  132,  132,  132,  132,   73,
       75,   76,  132,   79,  132,  132,   49,  132,  132,   84,
      132,   89,  132,  132,  132,  132,  132,  132,  132,  132,
      132,  132,  132,  132,   92,   95,   96,  132,  132,   58,
       59,  132,  132,  132,  132,  102,  132,   25,  132,  132,
      132,  132,  109,  132,  132,  132,  132,  115,  132,  132,
      132,  132,  132,   28,   62,  132,   32,  132,    3,    4,
       33,  132,   35,  132,  132,  132,   78,  132,   37,   80,
      132,   85,   86,  132,   41,   11,  132,  132,   42,  132,
      132,   20,  132,  132,  132,   93,  132,  127,   57,  132,

       98,  132,  132,  132,   61,  106,  132,  132,  110,  132,
      132,  112,  132,  132,  122,  132,  132,  132,  132,  132,
      132,   68,   70,   71,  132,  132,   81,    7,   15,   16,
      132,  132,  132,    9,   22,  132,  132,  132,  132,  132,
      132,  132,  132,  124,  132,  111,  132,  132,  132,  132,
      132,  132,   29,   13,    5,   34,  132,   14,  132,  132,
      132,   12,   21,  132,  132,   60,  132,  132,  101,  132,
      132,  132,  132,  132,  132,  132,  121,  132,  125,  132,
      132,   17,   19,   91,  132,  132,  100,  132,  132,  132,
      132,  132,  132,  119,  132,  132,  132,   97,  132,  132,

      132,  113,  132,  132,  132,  132,  132,  132,   38,   99,
      104,  107,  126,  132,  132,  132,  123,   72,  132,  132,
      132,  132,  114,  132,  132,  132,  132,  132,  132,  117,
      132,  132,  118,  120,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    4,    1,    1,    1,    1,    1,    1,
        1,    5,    1,    1,    6,    7,    1,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    1,    1,    1,
        1,    1,    5,    1,    9,   10,   11,   12,   13,   14,
       15,   16,   17,   18,   19,   20,   21,   22,   23,   24,
       25,   26,   27,   28,   29,   30,   31,   32,   33,   34,
        1,    1,    1,    1,    5,    1,   35,   36,   37,   38,

       39,   40,   41,   42,   43,   44,   45,   46,   47,   48,
       49,   50,   25,   51,   52,   53,   54,   55,   56,   57,
       58,   59,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[60] =
    {   0,
        1,    1,    2,    2,    3,    1,    1,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3
    } ;

static const flex_int16_t yy_base[539] =
    {   0,
        0,    0,    0,    0,    0,    0,  172, 1101,   58,   60,
        0,  159,  131,   57,   52,   56,   45,   57,   49,    0,
       62,  103,   65,   69,  142,  187,   94,  102,  108,  162,
      231,   52,  139,  141,  277, 1101,   81,  125,   83,  119,
      117,    0,   79,  104,  107,  125,  130,  163,  163,   81,
        0,  155,  204,  160,  172,  182,  163,  174,  176,  198,
      197,  207,  208,  238,  210,  226,  218,  240,  225,  250,
      250,  264,  282,  260,  241,  243,  263,  286,  275,  283,
      279,    0,  291,    0,  293,  297,  287,    0,  289,  319,
      316,  304,  314,  309,  327,  326,  338,  312,  333,  349,

      334,  354,  344,  342,  351,  326,  346,    0,  369,  377,
      367,  382,  382,  374, 1101,   80,  385,  377,  383,    0,
      391,    0,  382,  395,  375,  383,    0,  399,  387,  390,
      389,  397,  419,  403,  410,  407,  427,  409,  421,  434,
      435,  422,  431,  439,  428,  429,  440,  449,  436,  435,
      436,  443,  445,  440,  455,    0,  452,  456,    0,  473,
      461,    0,  477,  467,  471,  469,  479,  488,  491,  494,
      484,  478,  484,  483,  499,  487,  501,  504,  510,  499,
      497,  503,  509,  512,  509,  520,  524,  521,  528,    0,
      534,    0,  540,  539,  539,    0,  544,  534,  533,  555,

      541,  546,  546,  553,  547,  565,  575,  564,  549,  565,
      566,    0,  581,    0,    0,  582,  569,  573,  585,  594,
      592,    0,  580,  600,  585,  586,    0,  587,  590,  597,
      594,  595,  615,    0,  599,  617,  620,    0,    0,  618,
      622,    0,    0,  618,    0,  632,    0,  620,  633,  630,
      632,  637,    0,  630,  631,  634,  648,  635,  641,  646,
        0,  652,  652,  658,  654,  642,  645,  663,  665,  669,
      675,  673,    0,    0,  677,    0,  678,  680,  671,    0,
      680,  673,    0,  689,  681,  679,  693,  694,  690,  692,
      695,  684,    0,  695,    0,  702,  710,  697,    0,  695,

      707,  704,  721,  709,  716,  714,  716,  725,  737,    0,
        0,    0,  720,    0,  731,  721,    0,  723,  731,  726,
      746,    0,  733,  731,  737,  739,  742,  738,  751,  746,
      763,  767,  755,  760,  755,    0,  762,  764,  766,    0,
        0,  774,  773,  776,  788,    0,  782,    0,  783,  785,
      781,  800,    0,  785,  805,  792,  803,    0,  811,  812,
      812,  804,  819,    0,    0,  808,    0,  810,    0,  826,
        0,  821,    0,  812,  820,  811,    0,  824,  834,    0,
      822,    0,    0,  840,    0,    0,  827,  844,    0,  840,
      838,  841,  852,  854,  841,    0,  844,    0,    0,  853,

      846,  866,  852,  868,    0,  857,  860,  859,    0,  855,
      863,  882,  874,  877,    0,  874,  876,  877,  891,  882,
      898,    0,    0,  900,  903,  897,    0,    0,    0,  910,
      907,  895,  892,    0,    0,  900,  898,  915,  903,  920,
      909,  913,  910,    0,  913,    0,  913,  911,  935,  936,
      925,  944,    0,    0,    0,    0,  938,    0,  939,  937,
      934,    0,    0,  952,  944,    0,  948,  947,    0,  964,
      952,  966,  957,  955,  972,  973,    0,  964,    0,  966,
      982,    0,    0,    0,  980,  970,    0,  986,  976,  976,
      978,  997,  999, 1000,  988, 1007,  990,    0, 1007,  996,

     1010,    0, 1011, 1003,  997,  998, 1019, 1009,    0,    0,
        0,    0,    0, 1012, 1014, 1017,    0,    0, 1020, 1036,
     1037, 1040,    0, 1031, 1031, 1034, 1041, 1038, 1041,    0,
     1048, 1055,    0,    0, 1101, 1094, 1097,   75
    } ;

static const flex_int16_t yy_def[539] =
    {   0,
      535,    1,    1,    1,  536,  536,  535,  535,  535,  535,
      537,  535,  535,  535,  538,  538,  538,  538,  538,  538,
      538,  538,  538,  538,  538,  538,  538,  538,  538,  538,
      538,  538,  538,  538,  538,  535,  535,  537,  535,  535,
      535,  538,  538,  538,  538,  538,  538,  538,  538,  538,
      538,  538,  538,  538,  538,  538,  538,  538,  538,  538,
      538,  538,  538,  538,  538,  538,  538,  538,  538,  538,
      538,  538,  538,  538,  538,  538,  538,  538,  538,  538,
      538,  538,  538,  538,  538,  538,  538,  538,  538,  538,
      538,  538,  538,  538,  538,  538,  538,  538,  538,  538,

      538,  538,  538,  538,  538,  538,  538,  538,  538,  538,
      538,  538,  538,  538,  535,  535,  538,  538,  538,  538,
      538,  538,  538,  538,  538,  538,  538,  538,  538,  538,
      538,  538,  538,  538,  538,  538,  538,  538,  538,  538,
      538,  538,  538,  538,  538,  538,  538,  538,  538,  538,
      538,  538,  538,  538,  538,  538,  538,  538,  538,  538,
      538,  538,  538,  538,  538,  538,  538,  538,  538,  538,
      538,  538,  538,  538,  538,  538,  538,  538,  538,  538,
      538,  538,  538,  538,  538,  538,  538,  538,  538,  538,
      538,  538,  538,  538,  538,  538,  538,  538,  538,  538,

      538,  538,  538,  538,  538,  538,  538,  538,  538,  538,
      538,  538,  538,  538,  538,  538,  538,  538,  538,  538,
      538,  538,  538,  538,  538,  538,  538,  538,  538,  538,
      538,  538,  538,  538,  538,  538,  538,  538,  538,  538,
      538,  538,  538,  538,  538,  538,  538,  538,  538,  538,
      538,  538,  538,  538,  538,  538,  538,  538,  538,  538,
      538,  538,  538,  538,  538,  538,  538,  538,  538,  538,
      538,  538,  538,  538,  538,  538,  538,  538,  538,  538,
      538,  538,  538,  538,  538,  538,  538,  538,  538,  538,
      538,  538,  538,  538,  538,  538,  538,  538,  538,  538,

      538,  538,  538,  538,  538,  538,  538,  538,  538,  538,
      538,  538,  538,  538,  538,  538,  538,  538,  538,  538,
      538,  538,  538,  538,  538,  538,  538,  538,  538,  538,
      538,  538,  538,  538,  538,  538,  538,  538,  538,  538,
      538,  538,  538,  538,  538,  538,  538,  538,  538,  538,
      538,  538,  538,  538,  538,  538,  538,  538,  538,  538,
      538,  538,  538,  538,  538,  538,  538,  538,  538,  538,
      538,  538,  538,  538,  538,  538,  538,  538,  538,  538,
      538,  538,  538,  538,  538,  538,  538,  538,  538,  538,
      538,  538,  538,  538,  538,  538,  538,  538,  538,  538,

      538,  538,  538,  538,  538,  538,  538,  538,  538,  538,
      538,  538,  538,  538,  538,  538,  538,  538,  538,  538,
      538,  538,  538,  538,  538,  538,  538,  538,  538,  538,
      538,  538,  538,  538,  538,  538,  538,  538,  538,  538,
      538,  538,  538,  538,  538,  538,  538,  538,  538,  538,
      538,  538,  538,  538,  538,  538,  538,  538,  538,  538,
      538,  538,  538,  538,  538,  538,  538,  538,  538,  538,
      538,  538,  538,  538,  538,  538,  538,  538,  538,  538,
      538,  538,  538,  538,  538,  538,  538,  538,  538,  538,
      538,  538,  538,  538,  538,  538,  538,  538,  538,  538,

      538,  538,  538,  538,  538,  538,  538,  538,  538,  538,
      538,  538,  538,  538,  538,  538,  538,  538,  538,  538,
      538,  538,  538,  538,  538,  538,  538,  538,  538,  538,
      538,  538,  538,  538,    0,  535,  535,  535
    } ;

static const flex_int16_t yy_nxt[1161] =
    {   0,
        8,    9,   10,   11,    8,   12,   13,   14,   15,   16,
       17,   18,   19,   20,   21,   22,   23,   20,   24,   25,
       26,   27,   28,   29,   20,   30,   31,   32,   20,   20,
       33,   34,   20,   35,   15,   16,   17,   18,   19,   20,
       21,   22,   23,   20,   24,   25,   26,   27,   28,   29,
       30,   31,   32,   20,   20,   33,   34,   20,   35,   37,
       37,   37,   37,   41,   39,   43,   44,   52,   49,   53,
       55,   45,   50,   46,   57,   47,   67,   42,   48,  103,
       56,   69,   37,   37,  104,   54,   68,  116,   51,   41,
       39,   43,   44,   52,   49,   53,   55,   45,   50,   46,

       57,   47,   67,   48,  103,   56,  117,   69,  124,  104,
       54,   83,   68,   51,   58,   59,   81,   60,  118,   61,
       85,   62,   63,   64,  116,   82,   40,   84,  115,   65,
      119,  117,   66,  124,   86,   87,  120,   83,   40,   88,
       58,   59,   81,   60,  118,   61,   85,   62,   63,   64,
       82,  105,   84,  121,   65,  106,  119,   66,   70,   86,
       87,   71,  120,  107,   88,   72,   39,   73,   74,   75,
       89,  535,  108,  122,   90,  535,  123,  105,  125,  121,
      129,  106,  130,  535,   70,   91,  134,   71,  535,  107,
      133,   72,   73,   74,   75,   76,   89,  108,  131,  122,

       90,   77,  123,   78,  125,  132,  129,  135,  130,   79,
      136,   91,  134,   80,  126,  133,  535,  535,  137,  138,
      139,   76,  142,  127,  131,  535,  535,   77,  535,   78,
      128,  132,  135,  535,  143,   79,  136,  144,   80,   92,
      126,   93,   94,   95,  137,  138,  139,   96,  142,  127,
      145,   97,  140,   98,   99,  128,  100,  146,  101,  102,
      143,  535,  149,  144,  141,   92,  155,   93,   94,   95,
      147,  148,  154,   96,  156,  157,  145,   97,  140,   98,
       99,  100,  146,  101,  102,  109,  150,  110,  149,  141,
      152,  155,  151,  111,  153,  161,  147,  148,  154,  156,

      158,  157,  112,  113,  160,  114,  162,  159,  163,  166,
      168,  109,  150,  110,  167,  175,  152,  151,  164,  111,
      153,  161,  176,  535,  165,  177,  158,  112,  113,  160,
      114,  162,  169,  159,  163,  166,  168,  184,  173,  167,
      170,  175,  171,  164,  174,  172,  178,  180,  176,  165,
      182,  177,  181,  195,  179,  185,  188,  186,  169,  189,
      183,  187,  184,  192,  173,  193,  170,  194,  171,  174,
      172,  196,  178,  180,  190,  191,  182,  181,  195,  179,
      197,  185,  188,  186,  189,  198,  183,  187,  200,  192,
      201,  193,  203,  194,  202,  204,  196,  205,  207,  199,

      190,  191,  206,  208,  209,  210,  197,  212,  213,  214,
      215,  198,  216,  218,  200,  217,  201,  211,  203,  535,
      202,  204,  222,  205,  207,  199,  223,  206,  219,  208,
      209,  210,  212,  213,  224,  214,  215,  225,  216,  218,
      217,  226,  227,  211,  220,  221,  228,  229,  222,  230,
      231,  232,  223,  233,  219,  234,  235,  238,  239,  224,
      236,  535,  240,  225,  241,  242,  226,  243,  227,  220,
      221,  244,  228,  229,  230,  237,  231,  232,  233,  245,
      234,  246,  235,  238,  239,  247,  236,  240,  248,  249,
      241,  242,  243,  250,  251,  535,  252,  244,  253,  254,

      237,  255,  256,  257,  245,  258,  246,  259,  535,  260,
      261,  247,  262,  248,  263,  249,  264,  270,  250,  265,
      251,  252,  266,  271,  253,  254,  269,  255,  256,  257,
      258,  267,  274,  259,  260,  268,  261,  262,  272,  273,
      263,  275,  264,  270,  276,  265,  277,  278,  266,  271,
      279,  269,  280,  281,  282,  283,  535,  267,  274,  284,
      268,  285,  288,  272,  273,  286,  289,  275,  291,  292,
      276,  277,  293,  278,  297,  290,  279,  294,  280,  281,
      282,  283,  287,  295,  284,  296,  285,  298,  288,  299,
      300,  286,  289,  301,  291,  292,  302,  293,  303,  297,

      290,  304,  305,  294,  306,  535,  307,  287,  308,  295,
      309,  296,  310,  298,  311,  299,  300,  312,  313,  301,
      314,  302,  315,  303,  316,  535,  317,  304,  305,  318,
      306,  307,  319,  320,  308,  309,  321,  310,  322,  311,
      323,  324,  312,  325,  313,  314,  326,  315,  327,  328,
      316,  317,  329,  330,  331,  318,  332,  333,  319,  320,
      334,  335,  321,  336,  322,  337,  323,  324,  338,  325,
      339,  342,  326,  340,  327,  328,  341,  343,  329,  330,
      331,  344,  332,  333,  345,  346,  334,  335,  347,  336,
      348,  337,  349,  350,  338,  351,  339,  342,  340,  352,

      353,  341,  354,  343,  355,  356,  362,  344,  357,  363,
      345,  346,  358,  364,  347,  359,  348,  360,  349,  350,
      361,  351,  365,  368,  352,  366,  353,  367,  354,  355,
      369,  356,  362,  370,  357,  363,  371,  372,  358,  364,
      359,  373,  360,  374,  375,  361,  376,  378,  365,  368,
      366,  377,  367,  379,  380,  369,  381,  382,  383,  370,
      384,  371,  385,  372,  386,  387,  373,  388,  374,  389,
      375,  390,  376,  378,  391,  392,  377,  393,  379,  380,
      394,  381,  382,  395,  383,  384,  396,  385,  397,  386,
      387,  398,  388,  399,  389,  400,  402,  390,  401,  391,

      403,  392,  404,  393,  405,  394,  406,  535,  407,  395,
      408,  396,  409,  397,  410,  412,  398,  411,  399,  413,
      414,  400,  402,  401,  415,  416,  403,  417,  404,  418,
      405,  419,  406,  407,  420,  421,  408,  409,  422,  423,
      410,  412,  411,  424,  425,  413,  414,  426,  535,  427,
      415,  416,  428,  417,  429,  418,  430,  419,  431,  432,
      420,  421,  433,  422,  434,  423,  435,  438,  424,  436,
      425,  437,  439,  426,  427,  440,  535,  441,  428,  429,
      442,  445,  430,  443,  431,  432,  444,  446,  433,  447,
      434,  448,  435,  438,  436,  449,  437,  439,  450,  535,

      451,  440,  441,  452,  453,  454,  442,  445,  443,  455,
      456,  444,  446,  457,  447,  458,  459,  448,  460,  461,
      465,  449,  462,  463,  450,  451,  464,  466,  452,  453,
      467,  454,  468,  470,  455,  469,  456,  471,  472,  457,
      473,  458,  459,  474,  460,  461,  465,  462,  463,  475,
      476,  464,  478,  466,  477,  467,  479,  480,  468,  470,
      469,  481,  471,  472,  482,  473,  483,  484,  474,  485,
      486,  535,  487,  488,  489,  475,  476,  478,  490,  491,
      477,  492,  479,  480,  493,  494,  495,  481,  496,  482,
      497,  483,  498,  484,  485,  499,  486,  487,  500,  488,

      489,  501,  502,  503,  490,  491,  492,  504,  505,  506,
      493,  494,  495,  507,  496,  508,  497,  509,  498,  510,
      499,  511,  512,  513,  500,  514,  501,  502,  503,  515,
      516,  517,  523,  504,  505,  506,  518,  519,  507,  520,
      521,  508,  509,  522,  524,  510,  511,  525,  512,  513,
      526,  514,  527,  528,  515,  516,  529,  517,  523,  530,
      533,  518,  519,  531,  520,  521,  532,  534,  522,  535,
      524,  535,  535,  525,  535,  535,  526,  535,  527,  528,
      535,  535,  529,  535,  535,  530,  533,  535,  531,  535,
      535,  532,  535,  534,   36,   36,   36,   38,  535,   38,

        7,  535,  535,  535,  535,  535,  535,  535,  535,  535,
      535,  535,  535,  535,  535,  535,  535,  535,  535,  535,
      535,  535,  535,  535,  535,  535,  535,  535,  535,  535,
      535,  535,  535,  535,  535,  535,  535,  535,  535,  535,
      535,  535,  535,  535,  535,  535,  535,  535,  535,  535,
      535,  535,  535,  535,  535,  535,  535,  535,  535,  535
    } ;

static const flex_int16_t yy_chk[1161] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    9,
        9,   10,   10,   14,   14,   15,   15,   17,   16,   18,
       19,   15,   16,   15,   21,   15,   23,  538,   15,   32,
       19,   24,   37,   37,   32,   18,   23,  116,   16,   39,
       39,   15,   15,   17,   16,   18,   19,   15,   16,   15,

       21,   15,   23,   15,   32,   19,   43,   24,   50,   32,
       18,   28,   23,   16,   22,   22,   27,   22,   44,   22,
       29,   22,   22,   22,   41,   27,   40,   28,   38,   22,
       45,   43,   22,   50,   29,   29,   46,   28,   13,   29,
       22,   22,   27,   22,   44,   22,   29,   22,   22,   22,
       27,   33,   28,   47,   22,   33,   45,   22,   25,   29,
       29,   25,   46,   34,   29,   25,   12,   25,   25,   25,
       30,    7,   34,   48,   30,    0,   49,   33,   52,   47,
       54,   33,   55,    0,   25,   30,   58,   25,    0,   34,
       57,   25,   25,   25,   25,   26,   30,   34,   56,   48,

       30,   26,   49,   26,   52,   56,   54,   59,   55,   26,
       60,   30,   58,   26,   53,   57,    0,    0,   61,   62,
       63,   26,   65,   53,   56,    0,    0,   26,    0,   26,
       53,   56,   59,    0,   66,   26,   60,   67,   26,   31,
       53,   31,   31,   31,   61,   62,   63,   31,   65,   53,
       68,   31,   64,   31,   31,   53,   31,   69,   31,   31,
       66,    0,   71,   67,   64,   31,   75,   31,   31,   31,
       70,   70,   74,   31,   76,   77,   68,   31,   64,   31,
       31,   31,   69,   31,   31,   35,   72,   35,   71,   64,
       73,   75,   72,   35,   73,   80,   70,   70,   74,   76,

       78,   77,   35,   35,   79,   35,   81,   78,   83,   86,
       89,   35,   72,   35,   87,   92,   73,   72,   85,   35,
       73,   80,   93,    0,   85,   94,   78,   35,   35,   79,
       35,   81,   90,   78,   83,   86,   89,   98,   91,   87,
       90,   92,   90,   85,   91,   90,   95,   96,   93,   85,
       97,   94,   96,  106,   95,   99,  101,  100,   90,  101,
       97,  100,   98,  103,   91,  104,   90,  105,   90,   91,
       90,  107,   95,   96,  102,  102,   97,   96,  106,   95,
      109,   99,  101,  100,  101,  110,   97,  100,  111,  103,
      112,  104,  113,  105,  112,  114,  107,  117,  119,  110,

      102,  102,  118,  121,  123,  124,  109,  125,  126,  128,
      129,  110,  130,  132,  111,  131,  112,  124,  113,    0,
      112,  114,  134,  117,  119,  110,  135,  118,  133,  121,
      123,  124,  125,  126,  136,  128,  129,  137,  130,  132,
      131,  138,  139,  124,  133,  133,  140,  141,  134,  142,
      143,  144,  135,  145,  133,  146,  147,  149,  150,  136,
      148,    0,  151,  137,  152,  153,  138,  154,  139,  133,
      133,  155,  140,  141,  142,  148,  143,  144,  145,  157,
      146,  158,  147,  149,  150,  160,  148,  151,  161,  163,
      152,  153,  154,  164,  165,    0,  166,  155,  167,  168,

      148,  169,  170,  171,  157,  172,  158,  173,    0,  174,
      175,  160,  176,  161,  177,  163,  178,  181,  164,  179,
      165,  166,  179,  182,  167,  168,  180,  169,  170,  171,
      172,  179,  185,  173,  174,  179,  175,  176,  183,  184,
      177,  186,  178,  181,  187,  179,  188,  189,  179,  182,
      191,  180,  193,  194,  195,  197,    0,  179,  185,  198,
      179,  199,  201,  183,  184,  200,  202,  186,  203,  204,
      187,  188,  205,  189,  209,  202,  191,  206,  193,  194,
      195,  197,  200,  207,  198,  208,  199,  210,  201,  211,
      213,  200,  202,  216,  203,  204,  217,  205,  218,  209,

      202,  219,  220,  206,  221,    0,  223,  200,  224,  207,
      225,  208,  226,  210,  228,  211,  213,  229,  230,  216,
      231,  217,  232,  218,  233,    0,  235,  219,  220,  236,
      221,  223,  237,  240,  224,  225,  241,  226,  244,  228,
      246,  248,  229,  249,  230,  231,  250,  232,  251,  252,
      233,  235,  254,  255,  256,  236,  257,  258,  237,  240,
      259,  260,  241,  262,  244,  263,  246,  248,  264,  249,
      265,  268,  250,  266,  251,  252,  267,  269,  254,  255,
      256,  270,  257,  258,  271,  272,  259,  260,  275,  262,
      277,  263,  278,  279,  264,  281,  265,  268,  266,  282,

      284,  267,  285,  269,  286,  287,  292,  270,  288,  294,
      271,  272,  288,  296,  275,  289,  277,  290,  278,  279,
      291,  281,  297,  301,  282,  298,  284,  300,  285,  286,
      302,  287,  292,  303,  288,  294,  304,  305,  288,  296,
      289,  306,  290,  307,  308,  291,  309,  315,  297,  301,
      298,  313,  300,  316,  318,  302,  319,  320,  321,  303,
      323,  304,  324,  305,  325,  326,  306,  327,  307,  328,
      308,  329,  309,  315,  330,  331,  313,  332,  316,  318,
      333,  319,  320,  334,  321,  323,  335,  324,  337,  325,
      326,  338,  327,  339,  328,  342,  344,  329,  343,  330,

      345,  331,  347,  332,  349,  333,  350,    0,  351,  334,
      352,  335,  354,  337,  355,  357,  338,  356,  339,  359,
      360,  342,  344,  343,  361,  362,  345,  363,  347,  366,
      349,  368,  350,  351,  370,  372,  352,  354,  374,  375,
      355,  357,  356,  376,  378,  359,  360,  379,    0,  381,
      361,  362,  384,  363,  387,  366,  388,  368,  390,  391,
      370,  372,  392,  374,  393,  375,  394,  400,  376,  395,
      378,  397,  401,  379,  381,  402,    0,  403,  384,  387,
      404,  408,  388,  406,  390,  391,  407,  410,  392,  411,
      393,  412,  394,  400,  395,  413,  397,  401,  414,    0,

      416,  402,  403,  417,  418,  419,  404,  408,  406,  420,
      421,  407,  410,  424,  411,  425,  426,  412,  430,  431,
      437,  413,  432,  433,  414,  416,  436,  438,  417,  418,
      439,  419,  440,  442,  420,  441,  421,  443,  445,  424,
      447,  425,  426,  448,  430,  431,  437,  432,  433,  449,
      450,  436,  451,  438,  450,  439,  452,  457,  440,  442,
      441,  459,  443,  445,  460,  447,  461,  464,  448,  465,
      467,    0,  468,  470,  471,  449,  450,  451,  472,  473,
      450,  474,  452,  457,  475,  476,  478,  459,  480,  460,
      481,  461,  485,  464,  465,  486,  467,  468,  488,  470,

      471,  489,  490,  491,  472,  473,  474,  492,  493,  494,
      475,  476,  478,  495,  480,  496,  481,  497,  485,  499,
      486,  500,  501,  503,  488,  504,  489,  490,  491,  505,
      506,  507,  519,  492,  493,  494,  508,  514,  495,  515,
      515,  496,  497,  516,  520,  499,  500,  521,  501,  503,
      522,  504,  524,  525,  505,  506,  526,  507,  519,  527,
      531,  508,  514,  528,  515,  515,  529,  532,  516,    0,
      520,    0,    0,  521,    0,    0,  522,    0,  524,  525,
        0,    0,  526,    0,    0,  527,  531,    0,  528,    0,
        0,  529,    0,  532,  536,  536,  536,  537,    0,  537,

      535,  535,  535,  535,  535,  535,  535,  535,  535,  535,
      535,  535,  535,  535,  535,  535,  535,  535,  535,  535,
      535,  535,  535,  535,  535,  535,  535,  535,  535,  535,
      535,  535,  535,  535,  535,  535,  535,  535,  535,  535,
      535,  535,  535,  535,  535,  535,  535,  535,  535,  535,
      535,  535,  535,  535,  535,  535,  535,  535,  535,  535
    } ;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#line 1 "flex.l"
#line 2 "flex.l"
#include "bison_parser.h"
#include <stdio.h>
#include <sstream>
#include <string>
#include <cstring>
#define TOKEN(name) { return SQL_##name; }
static thread_local std::stringstream strbuf;
#line 1095 "flex_lexer.cpp"

#line 1097 "flex_lexer.cpp"

#define INITIAL 0
#define COMMENT 1
#define singlequotedstring 2

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

/* Holds the entire state of the reentrant scanner. */
struct yyguts_t
    {

    /* User-defined. Not touched by flex. */
    YY_EXTRA_TYPE yyextra_r;

    /* The rest are the same as the globals declared in the non-reentrant scanner. */
    FILE *yyin_r, *yyout_r;
    size_t yy_buffer_stack_top; /**< index of top of stack. */
    size_t yy_buffer_stack_max; /**< capacity of stack. */
    YY_BUFFER_STATE * yy_buffer_stack; /**< Stack as an array. */
    char yy_hold_char;
    int yy_n_chars;
    int yyleng_r;
    char *yy_c_buf_p;
    int yy_init;
    int yy_start;
    int yy_did_buffer_switch_on_eof;
    int yy_start_stack_ptr;
    int yy_start_stack_depth;
    int *yy_start_stack;
    yy_state_type yy_last_accepting_state;
    char* yy_last_accepting_cpos;

    int yylineno_r;
    int yy_flex_debug_r;

    char *yytext_r;
    int yy_more_flag;
    int yy_more_len;

    YYSTYPE * yylval_r;

    YYLTYPE * yylloc_r;

    }; /* end struct yyguts_t */

static int yy_init_globals ( yyscan_t yyscanner );

    /* This must go here because YYSTYPE and YYLTYPE are included
     * from bison output in section 1.*/
    #    define yylval yyg->yylval_r
    
    #    define yylloc yyg->yylloc_r
    
int yylex_init (yyscan_t* scanner);

int yylex_init_extra ( YY_EXTRA_TYPE user_defined, yyscan_t* scanner);

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( yyscan_t yyscanner );

int yyget_debug ( yyscan_t yyscanner );

void yyset_debug ( int debug_flag , yyscan_t yyscanner );

YY_EXTRA_TYPE yyget_extra ( yyscan_t yyscanner );

void yyset_extra ( YY_EXTRA_TYPE user_defined , yyscan_t yyscanner );

FILE *yyget_in ( yyscan_t yyscanner );

void yyset_in  ( FILE * _in_str , yyscan_t yyscanner );

FILE *yyget_out ( yyscan_t yyscanner );

void yyset_out  ( FILE * _out_str , yyscan_t yyscanner );

			int yyget_leng ( yyscan_t yyscanner );

char *yyget_text ( yyscan_t yyscanner );

int yyget_lineno ( yyscan_t yyscanner );

void yyset_lineno ( int _line_number , yyscan_t yyscanner );

int yyget_column  ( yyscan_t yyscanner );

void yyset_column ( int _column_no , yyscan_t yyscanner );

YYSTYPE * yyget_lval ( yyscan_t yyscanner );

void yyset_lval ( YYSTYPE * yylval_param , yyscan_t yyscanner );

       YYLTYPE *yyget_lloc ( yyscan_t yyscanner );
    
        void yyset_lloc ( YYLTYPE * yylloc_param , yyscan_t yyscanner );
    
/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( yyscan_t yyscanner );
#else
extern int yywrap ( yyscan_t yyscanner );
#endif
#endif

#ifndef YY_NO_UNPUT
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int , yyscan_t yyscanner);
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * , yyscan_t yyscanner);
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( yyscan_t yyscanner );
#else
static int input ( yyscan_t yyscanner );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg , yyscanner)
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex \
               (YYSTYPE * yylval_param, YYLTYPE * yylloc_param , yyscan_t yyscanner);

#define YY_DECL int yylex \
               (YYSTYPE * yylval_param, YYLTYPE * yylloc_param , yyscan_t yyscanner)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

    yylval = yylval_param;

    yylloc = yylloc_param;

	if ( !yyg->yy_init )
		{
		yyg->yy_init = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yyg->yy_start )
			yyg->yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack (yyscanner);
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE , yyscanner);
		}

		yy_load_buffer_state( yyscanner );
		}

	{
#line 27 "flex.l"

#line 1383 "flex_lexer.cpp"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yyg->yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yyg->yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yyg->yy_start;
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				yyg->yy_last_accepting_state = yy_current_state;
				yyg->yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 536 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_current_state != 535 );
		yy_cp = yyg->yy_last_accepting_cpos;
		yy_current_state = yyg->yy_last_accepting_state;

yy_find_action:
		yy_act = yy_accept[yy_current_state];

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yyg->yy_hold_char;
			yy_cp = yyg->yy_last_accepting_cpos;
			yy_current_state = yyg->yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 28 "flex.l"
TOKEN(DEL)
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 29 "flex.l"
TOKEN(DUMP)
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 30 "flex.l"
TOKEN(EXISTS)
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 31 "flex.l"
TOKEN(EXPIRE)
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 32 "flex.l"
TOKEN(EXPIREAT)
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 33 "flex.l"
TOKEN(KEYS)
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 34 "flex.l"
TOKEN(MIGRATE)
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 35 "flex.l"
TOKEN(COPY)
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 36 "flex.l"
TOKEN(REPLACE)
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 37 "flex.l"
TOKEN(MOVE)
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 38 "flex.l"
TOKEN(OBJECT)
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 39 "flex.l"
TOKEN(REFCOUNT)
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 40 "flex.l"
TOKEN(ENCODING)
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 41 "flex.l"
TOKEN(IDLETIME)
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 42 "flex.l"
TOKEN(PERSIST)
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 43 "flex.l"
TOKEN(PEXPIRE)
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 44 "flex.l"
TOKEN(PEXPIREAT)
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 45 "flex.l"
TOKEN(PTTL)
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 46 "flex.l"
TOKEN(RANDOMKEY)
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 47 "flex.l"
TOKEN(RENAME)
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 48 "flex.l"
TOKEN(RENAMENX)
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 49 "flex.l"
TOKEN(RESTORE)
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 50 "flex.l"
TOKEN(SORT)
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 51 "flex.l"
TOKEN(GET)
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 52 "flex.l"
TOKEN(STORE)
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 53 "flex.l"
TOKEN(TTL)
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 54 "flex.l"
TOKEN(TYPE)
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 56 "flex.l"
TOKEN(APPEND)
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 57 "flex.l"
TOKEN(BITCOUNT)
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 58 "flex.l"
TOKEN(BITOP)
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 59 "flex.l"
TOKEN(DECR)
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 60 "flex.l"
TOKEN(DECRBY)
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 61 "flex.l"
TOKEN(GETBIT)
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 62 "flex.l"
TOKEN(GETRANGE)
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 63 "flex.l"
TOKEN(GETSET)
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 64 "flex.l"
TOKEN(INCR)
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 65 "flex.l"
TOKEN(INCRBY)
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 66 "flex.l"
TOKEN(INCRBYFLOAT)
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 67 "flex.l"
TOKEN(MGET)
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 68 "flex.l"
TOKEN(MSET)
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 69 "flex.l"
TOKEN(MSETNX)
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 70 "flex.l"
TOKEN(PSETEX)
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 71 "flex.l"
TOKEN(SET)
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 72 "flex.l"
TOKEN(AND)
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 73 "flex.l"
TOKEN(OR)
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 74 "flex.l"
TOKEN(XOR)
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 75 "flex.l"
TOKEN(NOT)
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 76 "flex.l"
TOKEN(BY)
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 77 "flex.l"
TOKEN(LIMIT)
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 78 "flex.l"
TOKEN(ASC)
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 79 "flex.l"
TOKEN(DESC)
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 80 "flex.l"
TOKEN(ALPHA)
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 81 "flex.l"
TOKEN(EX)
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 82 "flex.l"
TOKEN(PX)
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 83 "flex.l"
TOKEN(NX)
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 84 "flex.l"
TOKEN(XX)
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 85 "flex.l"
TOKEN(SETBIT)
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 86 "flex.l"
TOKEN(SETEX)
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 87 "flex.l"
TOKEN(SETNX)
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 88 "flex.l"
TOKEN(SETRANGE)
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 89 "flex.l"
TOKEN(STRLEN)
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 90 "flex.l"
TOKEN(BEFORE)
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 91 "flex.l"
TOKEN(AFTER)
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 92 "flex.l"
TOKEN(SUM)
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 93 "flex.l"
TOKEN(MIN)
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 94 "flex.l"
TOKEN(MAX)
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 95 "flex.l"
TOKEN(HDEL)
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 96 "flex.l"
TOKEN(HEXISTS)
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 97 "flex.l"
TOKEN(HGET)
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 98 "flex.l"
TOKEN(HGETALL)
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 99 "flex.l"
TOKEN(HINCRBY)
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 100 "flex.l"
TOKEN(HINCRBYFLOAT)
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 101 "flex.l"
TOKEN(HKEYS)
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 102 "flex.l"
TOKEN(HLEN)
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 103 "flex.l"
TOKEN(HMGET)
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 104 "flex.l"
TOKEN(HMSET)
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 105 "flex.l"
TOKEN(HSET)
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 106 "flex.l"
TOKEN(HSETNX)
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 107 "flex.l"
TOKEN(HVALS)
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 108 "flex.l"
TOKEN(LINDEX)
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 109 "flex.l"
TOKEN(LINSERT)
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 110 "flex.l"
TOKEN(LLEN)
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 111 "flex.l"
TOKEN(LPOP)
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 112 "flex.l"
TOKEN(LPUSH)
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 113 "flex.l"
TOKEN(LPUSHX)
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 114 "flex.l"
TOKEN(LRANGE)
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 115 "flex.l"
TOKEN(LREM)
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 116 "flex.l"
TOKEN(LSET)
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 117 "flex.l"
TOKEN(LTRIM)
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 118 "flex.l"
TOKEN(RPOP)
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 119 "flex.l"
TOKEN(RPOPLPUSH)
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 120 "flex.l"
TOKEN(RPUSH)
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 121 "flex.l"
TOKEN(RPUSHX)
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 122 "flex.l"
TOKEN(SADD)
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 123 "flex.l"
TOKEN(SCARD)
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 124 "flex.l"
TOKEN(SDIFF)
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 125 "flex.l"
TOKEN(SDIFFSTORE)
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 126 "flex.l"
TOKEN(SINTER)
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 127 "flex.l"
TOKEN(SINTERSTORE)
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 128 "flex.l"
TOKEN(SISMEMBER)
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 129 "flex.l"
TOKEN(SMEMBERS)
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 130 "flex.l"
TOKEN(SMOVE)
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 131 "flex.l"
TOKEN(SPOP)
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 132 "flex.l"
TOKEN(SRANDMEMBER)
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 133 "flex.l"
TOKEN(SREM)
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 134 "flex.l"
TOKEN(SUNION)
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 135 "flex.l"
TOKEN(SUNIONSTORE)
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 136 "flex.l"
TOKEN(ZADD)
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 137 "flex.l"
TOKEN(ZCARD)
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 138 "flex.l"
TOKEN(ZCOUNT)
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 139 "flex.l"
TOKEN(ZINCRBY)
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 140 "flex.l"
TOKEN(ZRANGE)
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 141 "flex.l"
TOKEN(WITHSCORES)
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 142 "flex.l"
TOKEN(ZRANGEBYSCORE)
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 143 "flex.l"
TOKEN(ZRANK)
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 144 "flex.l"
TOKEN(ZREM)
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 145 "flex.l"
TOKEN(ZREMRANGEBYRANK)
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 146 "flex.l"
TOKEN(ZREMRANGEBYSCORE)
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 147 "flex.l"
TOKEN(ZREVRANGE)
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 148 "flex.l"
TOKEN(ZREVRANGEBYSCORE)
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 149 "flex.l"
TOKEN(ZREVRANK)
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 150 "flex.l"
TOKEN(ZSCORE)
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 151 "flex.l"
TOKEN(ZUNIONSTORE)
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 152 "flex.l"
TOKEN(WEIGHTS)
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 153 "flex.l"
TOKEN(AGGREGATE)
	YY_BREAK
case 126:
YY_RULE_SETUP
#line 154 "flex.l"
TOKEN(ZINTERSTORE)
	YY_BREAK
case 127:
YY_RULE_SETUP
#line 155 "flex.l"
TOKEN(SELECT)
	YY_BREAK
case 128:
#line 159 "flex.l"
case 129:
YY_RULE_SETUP
#line 159 "flex.l"
{
	yylval->fval = atof(yytext);
	return SQL_FLOATLITERAL;
	}
	YY_BREAK
case 130:
YY_RULE_SETUP
#line 164 "flex.l"
{
	yylval->ival = atol(yytext);
	return SQL_INTLITERAL;
	}
	YY_BREAK
case 131:
YY_RULE_SETUP
#line 169 "flex.l"
{
	std::string s(yytext);
	yylval->sval = strdup(s.substr(1, s.size()-1).c_str());
	return SQL_STRINGLITERAL;
	}
	YY_BREAK
case 132:
YY_RULE_SETUP
#line 175 "flex.l"
{
	yylval->sval = strdup(yytext);
	return SQL_IDENTIFIER;
	
	}
	YY_BREAK
case 133:
/* rule 133 can match eol */
YY_RULE_SETUP
#line 181 "flex.l"
{
	}
	YY_BREAK
case 134:
YY_RULE_SETUP
#line 184 "flex.l"
{
	return 0;
	}
	YY_BREAK
case 135:
YY_RULE_SETUP
#line 188 "flex.l"
ECHO;
	YY_BREAK
#line 2126 "flex_lexer.cpp"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(COMMENT):
case YY_STATE_EOF(singlequotedstring):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yyg->yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yyg->yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yyg->yy_c_buf_p <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yyg->yy_c_buf_p = yyg->yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state( yyscanner );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state , yyscanner);

			yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yyg->yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yyg->yy_last_accepting_cpos;
				yy_current_state = yyg->yy_last_accepting_state;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer( yyscanner ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yyg->yy_did_buffer_switch_on_eof = 0;

				if ( yywrap( yyscanner ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yyg->yy_c_buf_p = yyg->yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yyg->yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yyg->yy_c_buf_p =
					yyg->yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state( yyscanner );

				yy_cp = yyg->yy_c_buf_p;
				yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yyg->yy_c_buf_p =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars];

				yy_current_state = yy_get_previous_state( yyscanner );

				yy_cp = yyg->yy_c_buf_p;
				yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = yyg->yytext_ptr;
	int number_to_move, i;
	int ret_val;

	if ( yyg->yy_c_buf_p > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yyg->yy_c_buf_p - yyg->yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yyg->yy_c_buf_p - yyg->yytext_ptr - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) (yyg->yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2) , yyscanner );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yyg->yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			yyg->yy_n_chars, num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	if ( yyg->yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  , yyscanner);
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yyg->yy_n_chars + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = yyg->yy_n_chars + number_to_move + (yyg->yy_n_chars >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size , yyscanner );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	yyg->yy_n_chars += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yyg->yytext_ptr = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (yyscan_t yyscanner)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	yy_current_state = yyg->yy_start;

	for ( yy_cp = yyg->yytext_ptr + YY_MORE_ADJ; yy_cp < yyg->yy_c_buf_p; ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yyg->yy_last_accepting_state = yy_current_state;
			yyg->yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 536 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state , yyscan_t yyscanner)
{
	int yy_is_jam;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner; /* This var may be unused depending upon options. */
	char *yy_cp = yyg->yy_c_buf_p;

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yyg->yy_last_accepting_state = yy_current_state;
		yyg->yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 536 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 535);

	(void)yyg;
	return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (yyscan_t yyscanner)
#else
    static int input  (yyscan_t yyscanner)
#endif

{
	int c;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	*yyg->yy_c_buf_p = yyg->yy_hold_char;

	if ( *yyg->yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yyg->yy_c_buf_p < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] )
			/* This was really a NUL. */
			*yyg->yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = (int) (yyg->yy_c_buf_p - yyg->yytext_ptr);
			++yyg->yy_c_buf_p;

			switch ( yy_get_next_buffer( yyscanner ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin , yyscanner);

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( yyscanner ) )
						return 0;

					if ( ! yyg->yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput(yyscanner);
#else
					return input(yyscanner);
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yyg->yy_c_buf_p = yyg->yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yyg->yy_c_buf_p;	/* cast for 8-bit char's */
	*yyg->yy_c_buf_p = '\0';	/* preserve yytext */
	yyg->yy_hold_char = *++yyg->yy_c_buf_p;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * @param yyscanner The scanner object.
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack (yyscanner);
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE , yyscanner);
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file , yyscanner);
	yy_load_buffer_state( yyscanner );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * @param yyscanner The scanner object.
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack (yyscanner);
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*yyg->yy_c_buf_p = yyg->yy_hold_char;
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( yyscanner );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yyg->yy_did_buffer_switch_on_eof = 1;
}

static void yy_load_buffer_state  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	yyg->yytext_ptr = yyg->yy_c_buf_p = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	yyg->yy_hold_char = *yyg->yy_c_buf_p;
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * @param yyscanner The scanner object.
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state ) , yyscanner );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2) , yyscanner );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file , yyscanner);

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * @param yyscanner The scanner object.
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf , yyscanner );

	yyfree( (void *) b , yyscanner );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file , yyscan_t yyscanner)

{
	int oerrno = errno;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	yy_flush_buffer( b , yyscanner);

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * @param yyscanner The scanner object.
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( yyscanner );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  @param yyscanner The scanner object.
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack(yyscanner);

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*yyg->yy_c_buf_p = yyg->yy_hold_char;
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		yyg->yy_buffer_stack_top++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( yyscanner );
	yyg->yy_did_buffer_switch_on_eof = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  @param yyscanner The scanner object.
 */
void yypop_buffer_state (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER , yyscanner);
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if (yyg->yy_buffer_stack_top > 0)
		--yyg->yy_buffer_stack_top;

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( yyscanner );
		yyg->yy_did_buffer_switch_on_eof = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (yyscan_t yyscanner)
{
	yy_size_t num_to_alloc;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if (!yyg->yy_buffer_stack) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		yyg->yy_buffer_stack = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								, yyscanner);
		if ( ! yyg->yy_buffer_stack )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset(yyg->yy_buffer_stack, 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		yyg->yy_buffer_stack_max = num_to_alloc;
		yyg->yy_buffer_stack_top = 0;
		return;
	}

	if (yyg->yy_buffer_stack_top >= (yyg->yy_buffer_stack_max) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = yyg->yy_buffer_stack_max + grow_size;
		yyg->yy_buffer_stack = (struct yy_buffer_state**)yyrealloc
								(yyg->yy_buffer_stack,
								num_to_alloc * sizeof(struct yy_buffer_state*)
								, yyscanner);
		if ( ! yyg->yy_buffer_stack )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset(yyg->yy_buffer_stack + yyg->yy_buffer_stack_max, 0, grow_size * sizeof(struct yy_buffer_state*));
		yyg->yy_buffer_stack_max = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state ) , yyscanner );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b , yyscanner );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr , yyscan_t yyscanner)
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) , yyscanner);
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n , yyscanner );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n , yyscanner);
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;
	fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = yyg->yy_hold_char; \
		yyg->yy_c_buf_p = yytext + yyless_macro_arg; \
		yyg->yy_hold_char = *yyg->yy_c_buf_p; \
		*yyg->yy_c_buf_p = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the user-defined data for this scanner.
 * @param yyscanner The scanner object.
 */
YY_EXTRA_TYPE yyget_extra  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyextra;
}

/** Get the current line number.
 * @param yyscanner The scanner object.
 */
int yyget_lineno  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        if (! YY_CURRENT_BUFFER)
            return 0;
    
    return yylineno;
}

/** Get the current column number.
 * @param yyscanner The scanner object.
 */
int yyget_column  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        if (! YY_CURRENT_BUFFER)
            return 0;
    
    return yycolumn;
}

/** Get the input stream.
 * @param yyscanner The scanner object.
 */
FILE *yyget_in  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyin;
}

/** Get the output stream.
 * @param yyscanner The scanner object.
 */
FILE *yyget_out  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyout;
}

/** Get the length of the current token.
 * @param yyscanner The scanner object.
 */
int yyget_leng  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyleng;
}

/** Get the current token.
 * @param yyscanner The scanner object.
 */

char *yyget_text  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yytext;
}

/** Set the user-defined data. This data is never touched by the scanner.
 * @param user_defined The data to be associated with this scanner.
 * @param yyscanner The scanner object.
 */
void yyset_extra (YY_EXTRA_TYPE  user_defined , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyextra = user_defined ;
}

/** Set the current line number.
 * @param _line_number line number
 * @param yyscanner The scanner object.
 */
void yyset_lineno (int  _line_number , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        /* lineno is only valid if an input buffer exists. */
        if (! YY_CURRENT_BUFFER )
           YY_FATAL_ERROR( "yyset_lineno called with no buffer" );
    
    yylineno = _line_number;
}

/** Set the current column.
 * @param _column_no column number
 * @param yyscanner The scanner object.
 */
void yyset_column (int  _column_no , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        /* column is only valid if an input buffer exists. */
        if (! YY_CURRENT_BUFFER )
           YY_FATAL_ERROR( "yyset_column called with no buffer" );
    
    yycolumn = _column_no;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * @param yyscanner The scanner object.
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyin = _in_str ;
}

void yyset_out (FILE *  _out_str , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyout = _out_str ;
}

int yyget_debug  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yy_flex_debug;
}

void yyset_debug (int  _bdebug , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yy_flex_debug = _bdebug ;
}

/* Accessor methods for yylval and yylloc */

YYSTYPE * yyget_lval  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yylval;
}

void yyset_lval (YYSTYPE *  yylval_param , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yylval = yylval_param;
}

YYLTYPE *yyget_lloc  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yylloc;
}
    
void yyset_lloc (YYLTYPE *  yylloc_param , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yylloc = yylloc_param;
}
    
/* User-visible API */

/* yylex_init is special because it creates the scanner itself, so it is
 * the ONLY reentrant function that doesn't take the scanner as the last argument.
 * That's why we explicitly handle the declaration, instead of using our macros.
 */
int yylex_init(yyscan_t* ptr_yy_globals)
{
    if (ptr_yy_globals == NULL){
        errno = EINVAL;
        return 1;
    }

    *ptr_yy_globals = (yyscan_t) yyalloc ( sizeof( struct yyguts_t ), NULL );

    if (*ptr_yy_globals == NULL){
        errno = ENOMEM;
        return 1;
    }

    /* By setting to 0xAA, we expose bugs in yy_init_globals. Leave at 0x00 for releases. */
    memset(*ptr_yy_globals,0x00,sizeof(struct yyguts_t));

    return yy_init_globals ( *ptr_yy_globals );
}

/* yylex_init_extra has the same functionality as yylex_init, but follows the
 * convention of taking the scanner as the last argument. Note however, that
 * this is a *pointer* to a scanner, as it will be allocated by this call (and
 * is the reason, too, why this function also must handle its own declaration).
 * The user defined value in the first argument will be available to yyalloc in
 * the yyextra field.
 */
int yylex_init_extra( YY_EXTRA_TYPE yy_user_defined, yyscan_t* ptr_yy_globals )
{
    struct yyguts_t dummy_yyguts;

    yyset_extra (yy_user_defined, &dummy_yyguts);

    if (ptr_yy_globals == NULL){
        errno = EINVAL;
        return 1;
    }

    *ptr_yy_globals = (yyscan_t) yyalloc ( sizeof( struct yyguts_t ), &dummy_yyguts );

    if (*ptr_yy_globals == NULL){
        errno = ENOMEM;
        return 1;
    }

    /* By setting to 0xAA, we expose bugs in
    yy_init_globals. Leave at 0x00 for releases. */
    memset(*ptr_yy_globals,0x00,sizeof(struct yyguts_t));

    yyset_extra (yy_user_defined, *ptr_yy_globals);

    return yy_init_globals ( *ptr_yy_globals );
}

static int yy_init_globals (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    yyg->yy_buffer_stack = NULL;
    yyg->yy_buffer_stack_top = 0;
    yyg->yy_buffer_stack_max = 0;
    yyg->yy_c_buf_p = NULL;
    yyg->yy_init = 0;
    yyg->yy_start = 0;

    yyg->yy_start_stack_ptr = 0;
    yyg->yy_start_stack_depth = 0;
    yyg->yy_start_stack =  NULL;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER , yyscanner );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state(yyscanner);
	}

	/* Destroy the stack itself. */
	yyfree(yyg->yy_buffer_stack , yyscanner);
	yyg->yy_buffer_stack = NULL;

    /* Destroy the start condition stack. */
        yyfree( yyg->yy_start_stack , yyscanner );
        yyg->yy_start_stack = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( yyscanner);

    /* Destroy the main struct (reentrant only). */
    yyfree ( yyscanner , yyscanner );
    yyscanner = NULL;
    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;

	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s , yyscan_t yyscanner)
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;
	return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;

	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 188 "flex.l"


